const { Resend } = require("resend");
const {
  setCors,
  getSupabase,
  ErrorCodes,
  sendSuccess,
  sendError,
  logError,
  isValidUUID,
  isValidEmail,
  applyRateLimit,
  isServiceConfigured
} = require("../../_utils");

const VALID_ROLES = ['editor', 'admin', 'view_only', 'client'];

module.exports = async function handler(req, res) {
  setCors(res);

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return sendError(res, "Method not allowed", ErrorCodes.METHOD_NOT_ALLOWED);
  }

  // Rate limiting: 20 invites per hour per user
  const rateLimited = applyRateLimit(req, res, 'workspace-invite', { maxRequests: 20, windowMs: 3600000 });
  if (rateLimited) return;

  const supabase = getSupabase();

  if (!supabase) {
    return sendError(res, "Database service is not available", ErrorCodes.CONFIG_ERROR);
  }

  try {
    const { workspaceId } = req.query;
    const { email, role, userId } = req.body;

    if (!email || !userId || !workspaceId) {
      return sendError(res, "Email, userId, and workspaceId are required", ErrorCodes.VALIDATION_ERROR);
    }

    if (!isValidUUID(workspaceId)) {
      return sendError(res, "Invalid workspaceId format", ErrorCodes.VALIDATION_ERROR);
    }

    if (!isValidUUID(userId)) {
      return sendError(res, "Invalid userId format", ErrorCodes.VALIDATION_ERROR);
    }

    if (!isValidEmail(email)) {
      return sendError(res, "Invalid email format", ErrorCodes.VALIDATION_ERROR);
    }

    // Validate role
    const assignedRole = role || 'editor';
    if (!VALID_ROLES.includes(assignedRole)) {
      return sendError(
        res,
        `Invalid role. Must be one of: ${VALID_ROLES.join(', ')}`,
        ErrorCodes.VALIDATION_ERROR
      );
    }

    // Check if user has permission to invite (must be owner or admin of workspace)
    const { data: membership, error: membershipError } = await supabase
      .from('workspace_members')
      .select('role, can_manage_team')
      .eq('workspace_id', workspaceId)
      .eq('user_id', userId)
      .single();

    if (membershipError && membershipError.code !== 'PGRST116') {
      logError('workspaces.invite.checkMembership', membershipError, { userId, workspaceId });
    }

    if (!membership) {
      return sendError(res, "You don't have access to this workspace", ErrorCodes.FORBIDDEN);
    }

    if (!membership.can_manage_team && membership.role !== 'owner') {
      return sendError(res, "You don't have permission to invite members", ErrorCodes.FORBIDDEN);
    }

    // Check if user already exists and is a member
    const { data: existingUser } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('email', email.toLowerCase())
      .single();

    if (existingUser) {
      const { data: existingMember } = await supabase
        .from('workspace_members')
        .select('id')
        .eq('workspace_id', workspaceId)
        .eq('user_id', existingUser.id)
        .single();

      if (existingMember) {
        return sendError(res, "This user is already a workspace member", ErrorCodes.VALIDATION_ERROR);
      }
    }

    // Check if there's already a pending invitation
    const { data: existingInvite } = await supabase
      .from('workspace_invitations')
      .select('id')
      .eq('workspace_id', workspaceId)
      .eq('email', email.toLowerCase())
      .eq('status', 'pending')
      .single();

    if (existingInvite) {
      return sendError(res, "An invitation has already been sent to this email", ErrorCodes.VALIDATION_ERROR);
    }

    // Create the invitation (invite_token is auto-generated by database default)
    const { data: invitation, error: inviteError } = await supabase
      .from('workspace_invitations')
      .insert({
        workspace_id: workspaceId,
        email: email.toLowerCase(),
        role: assignedRole,
        invited_by: userId,
        status: 'pending',
        expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString() // 7 days
      })
      .select('*, invite_token')
      .single();

    if (inviteError) {
      logError('workspaces.invite.createInvitation', inviteError, { workspaceId, email: '[REDACTED]' });
      return sendError(res, "Failed to create invitation", ErrorCodes.DATABASE_ERROR);
    }

    // The invite_token is auto-generated by the database
    const inviteToken = invitation.invite_token;
    console.log('Invitation created:', {
      inviteId: invitation.id,
      tokenPrefix: inviteToken?.substring(0, 8) + '...',
      tokenLength: inviteToken?.length,
      email: email.substring(0, 3) + '***'
    });

    // Get workspace name for the email
    const { data: workspace } = await supabase
      .from('workspaces')
      .select('name')
      .eq('id', workspaceId)
      .single();

    // Send email if Resend is configured
    if (isServiceConfigured('resend')) {
      const resend = new Resend(process.env.RESEND_API_KEY);

      const { data: inviterData } = await supabase
        .from('user_profiles')
        .select('full_name, email')
        .eq('id', userId)
        .single();

      const inviterName = inviterData?.full_name || inviterData?.email || 'A team member';
      const workspaceName = workspace?.name || 'a workspace';
      // Use APP_URL first (correct), ignore FRONTEND_URL (wrong domain)
      const appUrl = (process.env.APP_URL || 'https://woozysocials.com').trim();
      const inviteLink = `${appUrl}/accept-invite?token=${inviteToken}`;

      try {
        await resend.emails.send({
          from: 'Woozy Social <hello@woozysocials.com>',
          to: [email],
          subject: `${inviterName} invited you to join ${workspaceName} on Woozy Social`,
          html: `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; background-color: #f5f3ff;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
    <tr>
      <td align="center" style="padding: 40px 20px;">
        <table role="presentation" width="600" cellspacing="0" cellpadding="0" border="0" style="max-width: 600px;">
          <tr>
            <td align="center" style="padding: 30px 40px;">
              <h1 style="margin: 0; color: #6465f1; font-size: 28px; font-weight: 700;">You've been invited!</h1>
            </td>
          </tr>
          <tr>
            <td style="padding: 10px 40px 40px 40px;">
              <p style="margin: 0 0 20px 0; font-size: 16px; color: #374151; line-height: 1.6;">
                <strong>${inviterName}</strong> has invited you to join <strong>${workspaceName}</strong> on Woozy Social.
              </p>
              <p style="margin: 0 0 30px 0; font-size: 16px; color: #374151;">
                Role: <strong style="color: #6465f1;">${assignedRole}</strong>
              </p>
              <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center">
                <tr>
                  <td align="center">
                    <a href="${inviteLink}" target="_blank" style="display: inline-block; padding: 14px 30px; font-size: 16px; font-weight: 700; color: #6465f1; text-decoration: none; border: 2px solid #6465f1; border-radius: 8px;">
                      Accept Invitation
                    </a>
                  </td>
                </tr>
              </table>
              <p style="margin: 30px 0 0 0; font-size: 14px; color: #6b7280; line-height: 1.6; text-align: center;">
                This invitation expires in 7 days.
              </p>
            </td>
          </tr>
          <tr>
            <td style="padding: 20px 40px; border-top: 1px solid #e5e7eb;">
              <p style="margin: 0; font-size: 12px; color: #6b7280; text-align: center;">
                If the button doesn't work, copy and paste this link:<br>
                <a href="${inviteLink}" style="color: #6465f1; word-break: break-all;">${inviteLink}</a>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
        });
      } catch (emailError) {
        logError('workspaces.invite.sendEmail', emailError, { workspaceId });
        // Don't fail the request if email fails
      }
    }

    return sendSuccess(res, {
      invitation,
      debug: {
        tokenUsedInEmail: inviteToken,
        frontendUrl: (process.env.APP_URL || 'https://woozysocials.com').trim()
      }
    });

  } catch (error) {
    logError('workspaces.invite.handler', error);
    return sendError(res, "Failed to send invitation", ErrorCodes.INTERNAL_ERROR);
  }
};
